source 'http://rubygems.org'

gem 'rails', '3.0.10'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'
gem 'bootstrap_helpers', '0.0.1'

group :test do
  gem 'rspec-rails', ">=2.5.0"
end
