source 'http://rubygems.org'

gem 'rails', '3.0.10'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'
gem 'jquery-rails'
gem 'bootstrap_helpers'

group :test do
  gem 'rspec-rails', ">=2.5.0"
  gem 'capybara', :git=>'git://github.com/jnicklas/capybara.git'
  gem 'guard-rspec'
  gem 'libnotify',  :require => false if RUBY_PLATFORM =~ /linux/i
  gem 'rb-inotify', :require => false if RUBY_PLATFORM =~ /linux/i
  gem 'rb-fsevent', :require => false if RUBY_PLATFORM =~ /darwin/i
end
